### ISSUE TITLE
Sharp turns dont work

### ISSUE THREAD

**Issue by STCollier** [Eczbek/c-snake#3]
When I want to make a sharp turn and press the side arrow key and the up arrow key at the same time, it kills me. Pls fix or i cri

**Comment by STCollier** [comment]
Also add a restart button while you're at it it's annoying to quit everytime I lose

**Comment by Eczbek** [comment]
nop

**Comment by STCollier** [comment]
stop closing these I have valid issues >:(

also apples spawn inside the snake unnacceptable
